import type { Metadata } from "next";
import { Mulish, IBM_Plex_Sans, Geist } from "next/font/google";
import "./globals.css";
import "./fonts.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});


// SF Pro and DM Serif Text will be loaded via CSS since they're not available on Google Fonts

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Tele Credit",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", mulish.variable, ibmPlexSans.variable, "font-sans", geist.variable)}
      suppressHydrationWarning
    >
      <body className="">{children}</body>
    </html>
  );
}
